non-mac aarch64 need to use __asm__ volatile("yield" ::: "memory")
Getting this error on ubuntu-arm buildrunner:
```
70.52 /usr/src/ember/src/libs/shared/shared/threading/Spinlock.h: In member function 'void ember::Spinlock::lock()':
70.52 /usr/src/ember/src/libs/shared/shared/threading/Spinlock.h:20:27: error: '__yield' was not declared in this scope
70.52    20 | #define YIELD_INSTRUCTION __yield()
70.52       |                           ^~~~~~~
70.52 /usr/src/ember/src/libs/shared/shared/threading/Spinlock.h:54:33: note: in expansion of macro 'YIELD_INSTRUCTION'
70.52    54 |                                 YIELD_INSTRUCTION;
70.52       |
```